### PR TITLE
6 more patterns

### PR DESCRIPTION
**Pull request by ghost**
r-pentomino, acorn, a "block-laying switch engine", toad, beacon, and the Gosper glider gun.
Terms as used in the Wikipedia article on [Conway's Game of Life](https://en.wikipedia.org/wiki/Conway's_Game_of_Life).
I'm not sure, though, that they all work the way you'd expect.

### CODE REVIEW

**Comment by wasamasa** [comment]
Could you please align the pattern rows?  Just mark them all and hit `TAB`, that should do the trick.

**Comment by wasamasa** [comment]
Huh.  The preview looks as if the continuation lines are off, but in my editor all is fine.  I assume that's because you're mixing tabs and spaces.  Please select the changed area and run `M-x untabify` on it.

**Comment by wasamasa** [comment]
Great.  For the final step, squash all commits into one by rebasing, fixing up all follow-up commits onto the first one and force-pushing, then I'll merge this.

**Comment by wasamasa** [comment]
I could also do that step, just tell me if you'd prefer me to handle the merge manually.

**Comment by ghost** [comment]
Feel free to use this any way you like. I can't say I get git ...

**Comment by wasamasa** [comment]
I've verified that all patterns work as expected. Thanks again.  Merged.

**Pull request closed without merging**
