### PR TITLE
Add Badges for melpa versions

### PR DESCRIPTION
**Pull request by AdrieanKhisbe**
Just add badge to README, so we know the versions available :)

PS: I can set you up some basic regression tests if you are interested

### CODE REVIEW

**Comment by wasamasa** [comment]
I'm not sure what there is to regression-test to be fair, given how regression tests are added _after_ discovering and fixing a bug.  A unit testing suite would make more sense, but I'd rather add that myself with buttercup.

**Comment by AdrieanKhisbe** [comment]
wasn't maybe the good term.
I meant just testing basic loading of module and function is working, to detect major failures.

**Comment by AdrieanKhisbe** [comment]
buttercup?

**Comment by AdrieanKhisbe** [comment]
Ah yes indeed
https://github.com/jorgenschaefer/emacs-buttercup :D

**Comment by wasamasa** [comment]
Hm, this looks like it screws up formatting majorly.  Could you at least insert a line break between the badges and the gif?

**Comment by AdrieanKhisbe** [comment]
I thought I did but I messed up with the rst. :/ sorry

After a bit of struggling, a managed to do it.
But it feellt better with the short intro  before the img

**Comment by wasamasa** [comment]
After fiddling around for quite some time, I've decided that no matter how I place the badges, they make the README look crappy.  Therefore I'll close this.

**Pull request closed without merging**
